import type { Medicine } from '@/types/Medicine'

export const medicine: Medicine[] = [
  {
    id: 'lamictal',
    title: 'Lamictal',
    text: 'Lamictal is a medication that treats epilepsy and bipolar disorder. It works by stabilizing electrical activity in the brain. This helps prevent seizures and mood swings.',
    perBox: 30,
    dose: '100mg',
    amountPerDay: 2,
    type: 'antidepressant',
    active: true,
    scheduled: true,
  },
  {
    id: 'alventa',
    title: 'Alventa',
    text: 'Alventa is a medication that treats depression. It increases the amount of serotonin in your brain. This hormone helps regulate your mood. The brand name of this medication is Celexa®.',
    perBox: 98,
    dose: '150mg',
    amountPerDay: 1,
    type: 'antidepressant',
    active: true,
    scheduled: true,
  },
  {
    id: 'trittico',
    title: 'Trittico',
    text: 'Trittico is an antidepressant medication that comes in a tablet form. It treats obsessive-compulsive disorder. This mental health condition causes you to have frequent unwanted thoughts that make you perform repetitive behaviors.',
    perBox: 60,
    dose: '150mg',
    amountPerDay: 1,
    type: 'antidepressant',
    active: true,
    scheduled: false,
  },
  {
    id: 'lorazepam',
    title: 'Lorazepam',
    text: "Lorazepam is a type of antidepressant known as a selective serotonin reuptake inhibitor (SSRI). It's often used to treat depression, and also sometimes panic attacks, obsessive compulsive disorder (OCD) and post-traumatic stress disorder (PTSD).",
    perBox: 50,
    dose: '1mg',
    amountPerDay: 1,
    type: 'antidepressant',
    active: false,
    scheduled: false,
  },
]
